version: "3.1"

services:
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: fei2022
      MYSQL_USER: feiuser
      MYSQL_PASSWORD: fei123
      MYSQL_DATABASE: fei2022
    ports:
      - 4000:3306
    volumes:
      - ./mysqldata:/var/lib/mysql

  app:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
    environment:
      DDBB_NAME: fei2022
      DDBB_HOST: db
      DDBB_USER: feiuser
      DDBB_PASSWORD: fei123
      PHP_USER_ID: 1000
      PRODUCCION: 0
    ports:
      - 8000:80

  PHPMyAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: feiuser
      PMA_PASSWORD: fei123
    ports:
      - 8001:80
